In [1]:
import yfinance as yf
import pandas as pd

In [2]:
arm = yf.download("ARM", start="2024-07-01", end="2024-08-31")

[*********************100%%**********************]  1 of 1 completed

In [5]:
arm['Change'] = ((arm['Close'] - arm['Open']) / arm['Open']) * 100
arm['Vol'] = arm['Volume'].apply(lambda x: f"{x:,}")

In [6]:
arm

,Open,High,Low,Close,Adj Close,Volume,Change,Vol
Date,,,,,,,,
2024-07-01,163.429993,163.850006,152.550003,158.830002,158.830002,8387500,-2.814655,"8,387,500"
2024-07-02,156.850006,163.619995,155.270004,163.460007,163.460007,5753500,4.214218,"5,753,500"
2024-07-03,162.419998,170.660004,159.309998,168.240005,168.240005,6649300,3.583307,"6,649,300"
2024-07-05,172.000000,182.649994,169.600006,181.190002,181.190002,14231300,5.343025,"14,231,300"
2024-07-08,181.039993,186.380005,179.514999,184.699997,184.699997,9516800,2.021655,"9,516,800"
2024-07-09,186.100006,188.750000,179.110001,182.279999,182.279999,9236900,-2.052664,"9,236,900"
2024-07-10,183.389999,187.470001,178.500000,186.460007,186.460007,6986400,1.674032,"6,986,400"
2024-07-11,186.839996,187.279999,173.029999,173.190002,173.190002,10662200,-7.305713,"10,662,200"
2024-07-12,174.070007,183.050003,173.500000,181.179993,181.179993,8999700,4.084555,"8,999,700"
2024-07-15,182.110001,183.740005,176.860001,177.529999,177.529999,5469500,-2.514964,"5,469,500"
2024-07-16,180.000000,180.949997,172.539993,178.770004,178.770004,5767500,-0.683331,"5,767,500"
2024-07-17,169.979996,172.360001,161.529999,161.699997,161.699997,12350600,-4.871161,"12,350,600"
2024-07-18,165.850006,166.660004,152.220001,158.330002,158.330002,10996300,-4.534220,"10,996,300"
2024-07-19,162.850006,165.050003,160.630005,163.399994,163.399994,7106800,0.337727,"7,106,800"
2024-07-22,165.470001,168.789993,162.679993,163.550003,163.550003,6179100,-1.160330,"6,179,100"
2024-07-23,163.240005,173.229996,161.869995,171.699997,171.699997,8036800,5.182548,"8,036,800"
2024-07-24,167.149994,167.149994,157.179993,157.679993,157.679993,9321100,-5.665571,"9,321,100"
2024-07-25,151.679993,155.630005,140.000000,149.139999,149.139999,15996000,-1.674574,"15,996,000"
2024-07-26,155.360001,155.509995,145.610001,149.000000,149.000000,8156200,-4.093718,"8,156,200"
2024-07-29,146.380005,149.949997,138.710007,141.440002,141.440002,9603100,-3.374780,"9,603,100"
2024-07-30,140.729996,142.070007,129.100006,132.960007,132.960007,11738900,-5.521203,"11,738,900"
2024-07-31,143.410004,145.479996,138.940002,144.169998,144.169998,16513000,0.529945,"16,513,000"
2024-08-01,128.940002,134.869995,118.180000,121.510002,121.510002,30867184,-5.762370,"30,867,184"

In [7]:
intel = yf.download("INTC", start="2024-07-01", end="2024-08-31")

[*********************100%%**********************]  1 of 1 completed

In [8]:
intel['Change'] = ((intel['Close'] - intel['Open']) / intel['Open']) * 100
intel['Vol'] = intel['Volume'].apply(lambda x: f"{x:,}")

In [9]:
intel

,Open,High,Low,Close,Adj Close,Volume,Change,Vol
Date,,,,,,,,
2024-07-01,30.910000,31.020000,30.610001,30.840000,30.840000,32401800,-0.226463,"32,401,800"
2024-07-02,30.860001,31.309999,30.590000,31.070000,31.070000,35999300,0.680490,"35,999,300"
2024-07-03,31.120001,31.340000,30.910000,31.230000,31.230000,24065700,0.353466,"24,065,700"
2024-07-05,31.400000,32.340000,31.309999,32.020000,32.020000,45309400,1.974525,"45,309,400"
2024-07-08,33.029999,34.090000,32.820000,33.990002,33.990002,82315900,2.906458,"82,315,900"
2024-07-09,35.020000,35.220001,33.720001,34.590000,34.590000,97546900,-1.227871,"97,546,900"
2024-07-10,34.439999,34.970001,34.130001,34.869999,34.869999,52256200,1.248549,"52,256,200"
2024-07-11,35.029999,35.150002,33.310001,33.500000,33.500000,55213700,-4.367682,"55,213,700"
2024-07-12,33.770000,35.480000,33.770000,34.490002,34.490002,62792600,2.132073,"62,792,600"
2024-07-15,34.700001,35.230000,34.310001,34.459999,34.459999,39847900,-0.691647,"39,847,900"
2024-07-16,34.360001,34.450001,33.840000,34.340000,34.340000,28409900,-0.058209,"28,409,900"
2024-07-17,36.080002,37.160000,34.400002,34.459999,34.459999,112304200,-4.490030,"112,304,200"
2024-07-18,34.959999,36.299999,34.529999,34.869999,34.869999,84188600,-0.257438,"84,188,600"
2024-07-19,34.570000,34.580002,32.849998,32.980000,32.980000,69628700,-4.599364,"69,628,700"
2024-07-22,33.279999,33.410000,32.759998,33.369999,33.369999,48503700,0.270433,"48,503,700"
2024-07-23,32.959999,33.230000,32.830002,32.950001,32.950001,29466400,-0.030335,"29,466,400"
2024-07-24,32.529999,32.799999,31.660000,31.700001,31.700001,62216700,-2.551485,"62,216,700"
2024-07-25,31.370001,31.990000,30.950001,31.100000,31.100000,49774000,-0.860696,"49,774,000"
2024-07-26,31.430000,31.559999,31.020000,31.350000,31.350000,38352500,-0.254534,"38,352,500"
2024-07-29,31.420000,31.469999,30.790001,30.830000,30.830000,32342200,-1.877785,"32,342,200"
2024-07-30,30.850000,30.910000,30.010000,30.129999,30.129999,48256600,-2.333878,"48,256,600"
2024-07-31,30.540001,30.870001,30.280001,30.740000,30.740000,56110600,0.654875,"56,110,600"
2024-08-01,30.434999,30.709999,28.889999,29.049999,29.049999,84308297,-4.550683,"84,308,297"

In [12]:
intel.to_csv('intel.csv')